### ISSUE TITLE
Hummingbird stopped working after macOS upgrade

### ISSUE THREAD

**Issue by jakst** [finestructure/Hummingbird#27] opened 2020-04-21 11:21 UTC
I upgraded my macbook pro 16" to macOS 10.15.4 (19E287) today, and move/resize gestures in Hummingbird stopped working completely.

I've double checked that it still has the correct accessibility preferences, and tried reinstalling Hummingbird. I've also double checked key bindings.

Anyone else experiencing this?

**Comment by finestructure** [comment] 2020-04-21 12:00
Mmm, that sounds like accessibility access might be messed up. When you say you reinstalled, did you explicitly remove accessibility access, relaunch HB to get the prompt, and then add it back? That might help in case you haven't tried!

**Comment by finestructure** [comment] 2020-04-21 12:01
FWIW, I'm running 19E287 and it works fine.

**Comment by jakst** [comment] 2020-04-21 12:08
False alarm. The update seems to have timed the expiry of my trial period. Purchased a license and now it works again.

So follow up: Why did I not get prompted to purchase? Nothing in the app alarmed me that my trial was up.

**Comment by finestructure** [comment] 2020-04-21 13:01
That's odd - it should have! I'll review how that's being handled.

**Comment by finestructure** [comment] 2020-09-10 09:17
So that should definitely shown an alert. The only way this could happen is that license expiry was just a coincidence while the real issue was accessibilty settings.

Going to go ahead and close this now, please let me know if you're seeing further issues!

**Closed as completed by finestructure** 2020-09-10 09:17 UTC

**Comment by RoelN** [comment] 2023-01-05 08:07
Quick note to say I had the same happen. It just stopped working, and I didn't see any indication that it was time to purchase a license. Maybe I dismissed it before reading, but it would be nice if a permanent message was in the app's settings for instance.

Anyway, nice little tool, gladly bought a license!

**Comment by finestructure** [comment] 2023-01-05 11:10
Hi @RoelN , glad you like Hummingbird!

Just to confirm: you didn't have a license yet, were out of the two week trial window and the app _didn't_ show an alert when launching?

Also, the app should show a clickable link in place of "🎫 Registered copy" saying "⚠️ Unregistered – click to register" when that's the case. I'd be really interested to hear what you saw in the bottom right of the preferences screen in your case, if you can remember or reproduce somehow.

![CleanShot 2023-01-05 at 12 03 02@2x](https://user-images.githubusercontent.com/65520/210766438-d381fd39-2240-45b8-b3f7-f6f0c2a2846d.png)

**Comment by RoelN** [comment] 2023-01-05 11:54
Indeed it said that, but I figured that was just the link to the registration process (because before the trial ends, there's a similar message there as well, if I recall correctly).

I just realized I've been doing some rebooting to get my docking station and monitor setup working properly, it might be the case that a window _did_ pop up, but I ignored it as I was focusing on other things.

Anyway, maybe simply adding "Trial expired" somewhere with the "please register" message would be a quick and easy improvement?

**Comment by finestructure** [comment] 2023-01-05 11:56
> Anyway, maybe simply adding "Trial expired" somewhere with the "please register" message would be a quick and easy improvement?

Ah yes, good idea - that'd be easy enough :)
